### ISSUE TITLE
PJRC prop shield

### ISSUE THREAD

**Issue by hybridtheorist** [leethomason/OpenSaber#11]
Hi Lee, please clarify the type of PJRC prop shield you recommend. Is it the low cost one without motion sensor (since the BOM already includes a triple-axis accelerometer):  http://www.pjrc.com/store/prop_shield_lowcost.html, or is it the more expensive version which include the motion sensor: http://www.pjrc.com/store/prop_shield.html? Thanks.

**Comment by leethomason** [comment]
The Prop Shield version of the PCB does not have the accelerometer as a breakout board, so it uses the "full" prop shield: http://www.pjrc.com/store/prop_shield.html. (And under-uses it, honestly. The code is currently just using the accelerometer, not the gyroscope and other fancy functions.)

**Comment by leethomason** [comment]
Closing - have since stopped using the prop shield. (Although it was super handy. But removing saved a lot of space.)
