### ISSUE TITLE
Regarding capcitors and MOSFETs

### ISSUE THREAD

**Issue by hybridtheorist** [leethomason/OpenSaber#13]
I'm using a Luxeon Rebel Endor Star RGB High Power LED: http://www.ledsupply.com/leds/luxeon-rebel-endor-star-rgb-high-power-led. Based on a Vbat of 3.7V, 350 mA LED current and max LED Vf of 3.5V and 2.8V, the resistors I should use are 1 ohm 1/4 W and 2.7 ohm 1 W respectively.
Could you please clarify what type of capacitors (how many uF?) and MOSFET (IRF3205? IRF9530? Or it doesn't really matter?) you recommend for your current setup? Thank you!

**Comment by leethomason** [comment]
I went with typical Vf on the Luxeon, and got similar results:

```
Luxeon Rebel Endor (Tri-LED)
Standard Resistors
R 2.90 @ 350 75% [2.7 ohm]
G 3.15 @ 350 83% [1.8 ohm]
B 3.15 @ 350 83% [1.8 ohm]
```

The capacitor is recommended near the power boost / LED, but I've never measured anything on an oscilloscope. I'm using 47uF - a couple hundred uF is probable better, but they are big and need to fit.

Any logic level mosfet that can handle 1W will work.
Adafruit / Digikey has an amazing one: 
https://www.adafruit.com/product/355

And my favorite of a smaller package:
https://www.digikey.com/product-detail/en/infineon-technologies/IRLU024NPBF/IRLU024NPBF-ND/812400

But digikey has thousands of choices.
