### ISSUE TITLE
Update docs for v3 design!

### ISSUE THREAD

**Issue by leethomason** [leethomason/OpenSaber#8]
Uses the v5 PCB. (The versioning system could be better.)

**Comment by hybridtheorist** [comment]
Hi Lee, 
I've run into the 1st question: do you recommend using a DC Input Constant Current LED Driver with the Luxeon Rebel RGB LED? Or is the driver's function already covered by the V5 emitter PCB? Thank you so much.

All my best,
Bo

**Comment by leethomason** [comment]
The V5 circuit uses resistors, not drivers. (Efficiency wise, it's about 80%, compared to a buck-puck with is about 90%. Both pretty good.) The microcontroller monitors the voltage, and adjusts the pulse frequency so that the _average_ current to the LED is 350mA. This keeps the LED from over-heating and keeps the efficiency very high for a resistor approach.

Side note: when I last looked at LED drivers, they had 2 problems: 1) a little too big, and 2) drivers that had a dimmer / control line required 7V. Both were pretty big issues, but I haven't looked at the current gen of driver.

Another side note: Jacob over at Open Source Saber uses drivers if you want to see that approach: http://www.rocket-props.com/the-open-source-saber-project (the LT3476 which looks like it solves both the power and size issue. I don't see a through hole mounting, but interesting option if you don't mind the SMD mounting)

**Comment by leethomason** [comment]
@hybridtheorist Docs are updated for the current design. Please feel free to file issues on the docs as they come up.
